 #!/usr/bin/env bash
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
BATCH_SRC="$SCRIPT_DIR/src"
JARS_DIR="$SCRIPT_DIR/jars"
SHIM_DIR="$SCRIPT_DIR/shim"      # holds sitecustomize.py for Python 3.12 compat

# ── Spark ─────────────────────────────────────────────────────────────────────
SPARK_HOME="${SPARK_HOME:-/opt/spark}"
SPARK_SUBMIT="$SPARK_HOME/bin/spark-submit"

if [[ ! -x "$SPARK_SUBMIT" ]]; then
    echo "ERROR: spark-submit not found at $SPARK_SUBMIT"
    echo "       Set SPARK_HOME in your shell or .env."
    exit 1
fi

# ── Load .env ─────────────────────────────────────────────────────────────────
if [[ -f "$PROJECT_ROOT/.env" ]]; then
    set -a; source "$PROJECT_ROOT/.env"; set +a
    echo "Loaded .env from $PROJECT_ROOT/.env"
fi

# ── sitecustomize.py shim (typing.io fix for Python 3.12 + old PySpark) ──────
# Python auto-executes sitecustomize.py when it appears on PYTHONPATH,
# BEFORE any other import — including pyspark.  This is the only reliable
# injection point that fires ahead of Spark's own zip loader.
mkdir -p "$SHIM_DIR"
cat > "$SHIM_DIR/sitecustomize.py" << 'PYEOF'
# Auto-generated by submit.sh — do not edit manually.
# Shims typing.io for Python 3.12+ / PySpark <= 3.3 compatibility.
import sys, types, typing
if "typing.io" not in sys.modules:
    _m = types.ModuleType("typing.io")
    _m.BinaryIO = typing.BinaryIO
    _m.TextIO   = typing.TextIO
    _m.IO       = typing.IO
    sys.modules["typing.io"] = _m
PYEOF

# ── Collect JARs ─────────────────────────────────────────────────────────────
mkdir -p "$JARS_DIR"
JAR_LIST="$(find "$JARS_DIR" -name '*.jar' | paste -sd,)"
if [[ -z "$JAR_LIST" ]]; then
    echo "ERROR: No JARs in $JARS_DIR. Download them first (see script header)."
    exit 1
fi
echo "JARs: $(find "$JARS_DIR" -name '*.jar' -exec basename {} \; | tr '\n' ' ')"

# ── Package batch/src/ ────────────────────────────────────────────────────────
BATCH_ZIP="$PROJECT_ROOT/batch_src.zip"
cd "$BATCH_SRC"
zip -r "$BATCH_ZIP" . \
    --exclude '__pycache__/*' --exclude '**/__pycache__/*' --exclude '*.pyc' -q
echo "Packaged batch/src/ → $BATCH_ZIP"
cd "$PROJECT_ROOT"

# ── spark-submit ──────────────────────────────────────────────────────────────
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " Launching YouTube Batch Pipeline  |  args: $*"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

PYTHONPATH="$SHIM_DIR:${PYTHONPATH:-}" \
"$SPARK_SUBMIT" \
    --master "${SPARK_MASTER:-local[*]}" \
    --deploy-mode client \
    --driver-memory   "${SPARK_DRIVER_MEMORY:-4g}" \
    --executor-memory "${SPARK_EXECUTOR_MEMORY:-4g}" \
    --jars "$JAR_LIST" \
    --py-files "$BATCH_ZIP" \
    --conf "spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem" \
    --conf "spark.hadoop.fs.s3a.endpoint=http://${MINIO_ENDPOINT:-localhost:9002}" \
    --conf "spark.hadoop.fs.s3a.access.key=${MINIO_ACCESS_KEY:-minioadmin}" \
    --conf "spark.hadoop.fs.s3a.secret.key=${MINIO_SECRET_KEY:-minioadmin}" \
    --conf "spark.hadoop.fs.s3a.path.style.access=true" \
    --conf "spark.hadoop.fs.s3a.connection.ssl.enabled=false" \
    --conf "spark.hadoop.fs.s3a.aws.credentials.provider=org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider" \
    --conf "spark.serializer=org.apache.spark.serializer.KryoSerializer" \
    --conf "spark.sql.adaptive.enabled=true" \
    --conf "spark.sql.adaptive.coalescePartitions.enabled=true" \
    --conf "spark.driver.extraJavaOptions=-Dpython.path=$SHIM_DIR" \
    "$BATCH_SRC/pipeline.py" \
    "$@"

EXIT_CODE=$?
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " spark-submit exited: $EXIT_CODE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
exit $EXIT_CODE