channels:
  - id: UCsBjURrPoezykLs9EqgamOA
    name: Fireship

  - id: UCq8DICunczvLuJJq414110A
    name: Zach King

  - id: UCX6OQ3DkcsbYNE6H8uQQuVA
    name: MrBeast

#  - id: UCXuqSBlHAE6Xw-yeJA0Tunw
#    name: Linus Tech Tips

#  - id: UCBcRF18a7Qf58cCRy5xuWwQ
#    name: Marques Brownlee (MKBHD)

  - id: UC9x0AN7BWHpCDHSm9NiJFJQ
    name: NetworkChuck

  - id: UCVhQ2NnY5Rskt6UjCUkJ_DA
    name: Tech With Tim

  - id: UC3kf-QFT6FZzDk9JsPg8Svg
    name: Hello Interview

  - id: UC2bW_AY9BlbYLGJSXAbjS4Q
    name: Live Speedy

  - id: UCisy6taOAeLfyaCqcMQDfig
    name: Max Klymenko

  - id: UCqcxR9B59H4DT1e6hg1Smiw
    name: zi8gzag

  - id: UC415bOPUcGSamy543abLmRA
    name: Cleo Abram

  - id: UCnmGIkw-KdI0W5siakKPKog
    name: Ryan Trahan
