"""add_processed_for_cuts_to_downloaded_videos

Revision ID: 9474ae22b7bd
Revises: 26e208a0ac74
Create Date: 2026-05-28 20:46:52.519205+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '9474ae22b7bd'
down_revision: Union[str, None] = '26e208a0ac74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('downloaded_videos', sa.Column('processed_for_cuts', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('downloaded_videos', 'processed_for_cuts')
    # ### end Alembic commands ###
