apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: grafana-clickhouse-datasource
    isDefault: true
    access: proxy
    url: clickhouse:9000
    jsonData:
      server: clickhouse
      port: 9000
      username: admin
      tlsSkipVerify: true
    secureJsonData:
      password: admin
