apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: clickhouse_ds
    isDefault: true
    editable: true
    jsonData:
      server: clickhouse
      port: 9000
      username: ${CLICKHOUSE_USER:-admin}
      defaultDatabase: gold
      tlsSkipVerify: true
    secureJsonData:
      password: ${CLICKHOUSE_PASSWORD:-admin}
