# Auto-generated by submit.sh — do not edit manually.
# Shims typing.io for Python 3.12+ / PySpark <= 3.3 compatibility.
import sys, types, typing
if "typing.io" not in sys.modules:
    _m = types.ModuleType("typing.io")
    _m.BinaryIO = typing.BinaryIO
    _m.TextIO   = typing.TextIO
    _m.IO       = typing.IO
    sys.modules["typing.io"] = _m
